drop database if exists cms;

create database cms;

use CMS;

SHOW TABLES;


DROP TABLE IF EXISTS VENDOR;
CREATE TABLE vendor (
  VEN_ID int(10) unsigned NOT NULL AUTO_INCREMENT,
  VEN_NAME varchar(30) NOT NULL,
  VEN_NUMBER varchar(10) NOT NULL,
  VEN_USER_NAME varchar(15) NOT NULL,
  VEN_PASSWORD varchar(30) NOT NULL,
  VEN_EMAIL varchar(30) NOT NULL,
  VEN_ADDRESS varchar(50),
  PRIMARY KEY (`VEN_ID`)
) ;




DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE Customer (
  CUS_ID int(10) NOT NULL AUTO_INCREMENT,
  CUS_NAME varchar(50) NOT NULL,
  CUS_PHNNO varchar(50) NOT NULL,
  CUS_USERNAME varchar(50) NOT NULL,
  CUS_PASSWORD varchar(50) NOT NULL,
  CUS_EMAIL varchar(50) NOT NULL,
  CUS_DOB date,
  CUS_ADDRESS varchar(100),
  PRIMARY KEY (CUS_ID),
  UNIQUE KEY CUS_PHNNO (CUS_PHNNO),
  UNIQUE KEY CUS_USERNAME (CUS_USERNAME)
);

INSERT INTO VENDOR(VEN_ID,VEN_NAME,VEN_NUMBER,VEN_USER_NAME,VEN_PASSWORD,VEN_EMAIL,VEN_ADDRESS) VALUES(1,'Naina',9999999999,'naina1','naina@123','naina@gmail.com','Jamshedpur');
INSERT INTO VENDOR(VEN_ID,VEN_NAME,VEN_NUMBER,VEN_USER_NAME,VEN_PASSWORD,VEN_EMAIL,VEN_ADDRESS) VALUES(2,'Sparsh',9888888888,'sparsh2','sparsh@123','sparsh@gmail.com','JAIPUR');
INSERT INTO VENDOR(VEN_ID,VEN_NAME,VEN_NUMBER,VEN_USER_NAME,VEN_PASSWORD,VEN_EMAIL,VEN_ADDRESS) VALUES(3,'Vedant',9777777777,'vedant3','vedant@123','vedant@gmail.com','Jamshedpur');
INSERT INTO VENDOR(VEN_ID,VEN_NAME,VEN_NUMBER,VEN_USER_NAME,VEN_PASSWORD,VEN_EMAIL,VEN_ADDRESS) VALUES(4,'Shilpa',9666666666,'shilpa4','shilpa@123','shilpa@gmail.com','Bhubaneswar');
INSERT INTO VENDOR(VEN_ID,VEN_NAME,VEN_NUMBER,VEN_USER_NAME,VEN_PASSWORD,VEN_EMAIL,VEN_ADDRESS) VALUES(5,'Megh',9555555555,'megh5','megh@123','megh@gmail.com','BBSR');

select * from vendor;


DROP TABLE IF EXISTS ORDERS;

CREATE TABLE ORDERS
(
ORD_ID INT (10) NOT NULL AUTO_INCREMENT,
CUS_ID INT(10) unsigned NOT NULL REFERENCES CUSTOMER(CUS_Id),
VEN_ID INT(10) unsigned NOT NULL REFERENCES VENDOR(VEN_ID),
MEN_ID INT(10) NOT NULL REFERENCES MENU(MEN_ID),
WAL_SOURCE Varchar(30),
ORD_DATE date,
ORD_QTY INT,
ORD_BILLAMOUNT double,
ORD_STATUS ENUM('ACCEPTED','DENIED','PENDING','CANCELLED') DEFAULT 'PENDING',
ORD_COMMENTS varchar(50) DEFAULT NULL,
PRIMARY KEY(ORD_ID)
);


INSERT INTO CUSTOMER(CUS_ID,CUS_NAME,CUS_PHNNO,CUS_USERNAME,CUS_PASSWORD,CUS_EMAIL,CUS_DOB,CUS_ADDRESS)
VALUES (1,'Nikhil','9000000009','nikhil1','nikhil@123', 'nikhil@gmail.com','1997-05-16','CHENNAI'),
       (2,'Arpita','9111111119','arpita2','arpita@123', 'arpita@gmail.com','1998-01-07','KOLKATA'),
       (3,'Ashmita','9222222229','ashmita3','ashmita@123', 'ashmita@gmmail.com','1997-02-14','BANGLORE'),
       (4,'Ayush','9333333339','ayush4','ayush@123', 'ayush@gmmail.com','1997-06-06','JAMSHEDPUR');


CREATE TABLE Menu (
  MENU_ID int(10)  NOT NULL AUTO_INCREMENT,
  MENU_ITEM varchar(50) DEFAULT NULL,
  MENU_PRICE numeric(8,2),
  MENU_CALORIES double NOT NULL,
  MENU_TYPE varchar(50) NOT NULL,
  MENU_STATUS enum('AVAILABLE' , 'NOTAVAILABLE') DEFAULT ('AVAILABLE'),
  MENU_RATING varchar(75),
  PRIMARY KEY (MENU_ID)
);
INSERT INTO MENU(MENU_ID,MENU_ITEM,MENU_PRICE,MENU_CALORIES,MENU_TYPE,MENU_STATUS,MENU_RATING)
VALUES
(1," VEG BIRYANI",'80','241','VEG','AVAILABLE','3'),
(2,"PURI SABJI",'30','414','VEG','AVAILABLE','4'),
(3,"PAV BHAJI",'45','400','VEG','AVAILABLE','4'),
(4,"VEG THALI",'60','650','VEG','AVAILABLE','3'),
(5,"FISH FRY",'90','210','NONVEG','AVAILABLE','5'),
(6,"CHICKEN BIRYANI",'120','390','NONVEG','AVAILABLE','5');


CREATE TABLE WALLET
(
Cus_Id int(10) unsigned DEFAULT NULL references customer(Cus_Id),
Wal_Id int(10) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
Wal_Amount double unsigned NOT NULL,
Wal_Source Enum('CREDITCARD','DEBITCARD','PAYTM') DEFAULT('DEBITCARD'),
UNIQUE KEY(Cus_Id,Wal_Source)
);

INSERT INTO WALLET(Cus_Id,Wal_Amount,Wal_Source)
values
(1,2000,'PAYTM'),
(1,1200,'DEBITCARD'),
(1,8000,'CREDITCARD'),
(2,5000,'DEBITCARD'),
(2,250,'PAYTM'),
(3,1500,'CREDITCARD'),
(4,4500,'DEBITCARD'),
(4,6000,'PAYTM');

 

SHOW TABLES;